image: "docker.elastic.co/beats/filebeat"

imageTag: "7.15.1"

imagePullPolicy: "IfNotPresent"

resources:

  requests:

    cpu: "100m"

    memory: "100Mi"

  limits:

    cpu: "1000m"

    memory: "200Mi"